[local]
localhost 

[mongodb]
localhost

[catalogue]
catalogue-dev.pavanreddy.online

[redis]
localhost

[user]
user-dev.pavanreddy.online

[cart]
cart-dev.pavanreddy.online

[mysql]
mysql-dev.pavanreddy.online

[shipping]
shipping-dev.pavanreddy.online

[rabbitmq]
rabbitmq-dev.pavanreddy.online

[payment]
payment-dev.pavanreddy.online

[frontend]
frontend-dev.pavanreddy.online