[local]
localhost 

[mongodb]
localhost ansible_connection=local

[catalogue]
localhost 

[redis]
localhost ansible_connection=local

[user]
localhost

[cart]
localhost

[mysql]
localhost ansible_connection=local

[shipping]
localhost

[rabbitmq]
localhost

[payment]
localhost

[frontend]
localhost 