- name: call common role using import_role
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "Redhat"

# - name: call common role using include_role
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: include-vs-import.yaml
#   when: os == "Redhat"
#   loop:
#    - Pavan 
#    - Reddy 